# Generated by Django 2.1.5 on 2021-02-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210213_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplied_by',
            new_name='supplier',
        ),
    ]
